name: Semver
description: "Increments the base or last tag by the increment or version, supports custom prefixes like chart-name-1.2.3."
author: "mbround18"

inputs:
  token:
    description: "GitHub token for authentication with GraphQL API."
    required: false
    default: "${{ github.token }}"
  base:
    description: "Base version to start from. If not provided, the last matching tag will be used."
    required: false
    default: ""
  prefix:
    description: "Optional prefix used to filter and build tag versions. Example: 'chart-name-' -> chart-name-1.2.3"
    required: false
    default: ""
  increment:
    description: "Increment value (major, minor, patch). If not provided, will infer from PR or commit labels."
    required: false
    default: "patch"
  major-label:
    description: "Label to identify a major increment (default: 'major')."
    required: false
    default: "major"
  minor-label:
    description: "Label to identify a minor increment (default: 'minor')."
    required: false
    default: "minor"
  patch-label:
    description: "Label to identify a patch increment (default: 'patch')."
    required: false
    default: "patch"

outputs:
  new_version:
    description: "Outputs the incremented version based on input parameters"

runs:
  using: "docker"
  image: "Dockerfile"
