query getAssociatedPRLabels(
  $owner: String!
  $repo: String!
  $commitSha: GitObjectID!
) {
  repository(owner: $owner, name: $repo) {
    object(oid: $commitSha) {
      ... on Commit {
        associatedPullRequests(first: 1) {
          nodes {
            title
            number
            labels(first: 10) {
              nodes {
                name
              }
            }
          }
        }
      }
    }
  }
}
