name: Setup Rust
description: "Setus up rust with clis as needed."
author: "mbround18"
inputs:
  toolchain:
    description: "Toolchain to utilize"
    default: "stable"
  components:
    description: "Components to install"
    default: ""
  crates:
    description: "A comma-separated list of crates"
    required: true
    default: "crate1,crate2,trunk"
runs:
  using: "composite"
  steps:
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.events.inputs.toolchain }}
        components: ${{ github.events.inputs.components }}

    - name: Cache Cargo Registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo Index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Run trunk action if trunk is in crates
      if: contains(github.event.inputs.crates, 'trunk')
      uses: mbround18/gh-reusable/actions/setup-rust@main
      inputs:
        repository: trunk-rs/trunk
        version: latest
        asset: trunk-x86_64-unknown-linux-gnu.tar.gz
