name: Setup Rust
description: "Sets up Rust toolchains, components, and additional CLI tools as needed."
author: "mbround18"
inputs:
  toolchain:
    description: "Rust toolchain to use (e.g., stable, nightly, beta)."
    default: "stable"
  components:
    description: "Comma-separated list of Rust components to install (e.g., rustfmt, clippy)."
    default: ""
  target:
    description: "Comma-separated list of additional Rust compilation targets."
    default: ""
  crates:
    description: "Comma-separated list of CLI crates to install (e.g., trunk, wasm-bindgen)."
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        target: "${{ inputs.target }}"

    - name: Cache Cargo Registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.toolchain }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-${{ inputs.toolchain }}
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo Index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.toolchain }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-${{ inputs.toolchain }}
          ${{ runner.os }}-cargo-index-

    - name: Install Rust Crates
      shell: bash
      run: |
        IFS=',' read -ra CRATES <<< "${{ inputs.crates }}"
        for crate in "${CRATES[@]}"; do
          if [ "$crate" != "trunk" ]; then
            cargo install "$crate"
          fi
        done

    - name: Install Trunk if Specified
      if: contains(inputs.crates, 'trunk')
      uses: mbround18/gh-reusable/actions/install-cli@main
      with:
        repository: trunk-rs/trunk
        version: latest
        asset: trunk-x86_64-unknown-linux-gnu.tar.gz
