name: "Docker Facts"
description: "Extract dockerfile, context, and build args from docker-compose.yml"
author: "Michael Bruno"
inputs:
  image:
    description: "The name of the image to build"
    required: true
  version:
    description: "The version to tag the image with"
    required: true
  registries:
    description: "Comma-separated list of registries to push to"
    required: false
    default: ""
  dockerfile:
    description: "Path to the Dockerfile (fallback if not found in docker-compose)"
    required: false
    default: "./Dockerfile"
  context:
    description: "Path to the build context (fallback if not found in docker-compose)"
    required: false
    default: "."
  canary_label:
    description: "Label to check for when determining if a canary build should be pushed"
    required: false
    default: "canary"
  force_push:
    description: "Force push the image even if conditions are not met"
    required: false
    default: "false"
  with_latest:
    description: "Also tag the image with latest"
    required: false
    default: "false"
  target:
    description: "Target stage to build"
    required: false
    default: ""
  prepend_target:
    description: "Prepend target to the tag name"
    required: false
    default: "false"
outputs:
  dockerfile:
    description: "Path to the Dockerfile to use"
  context:
    description: "Path to the build context to use"
  target:
    description: "Target stage to build (if any)"
  push:
    description: "Whether to push the image (true/false)"
  tags:
    description: "Comma-separated list of tags to apply to the image"

runs:
  using: "docker"
  image: "Dockerfile"
