on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        default: "mbround18/example"
        description: "Image Name"
      dockerfile:
        type: string
        default: "./Dockerfile"
        description: "Dockerfile"
    secrets:
      DOCKER_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: mbround18
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ inputs.image }}:buildcache
          cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
          build-args: |
            GITHUB_SHA=${GITHUB_SHA}
            GITHUB_REF=${GITHUB_REF}
            GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
            IMAGE_VERSION=${{ steps.meta.outputs.version }}

      - name: Output image information
        run: |
          echo "Exported Image:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`${{ steps.meta.outputs.tags }}\`\`\`" >> $GITHUB_STEP_SUMMARY
