name: test ci
on:
  push:

defaults:
  run:
    working-directory: ./actions/install-cli

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -l 
    