name: "Rust Build and Test"

on:
  workflow_call:
    inputs:
      toolchain:
        required: false
        type: string
        description: "Rust toolchain to use (e.g., stable, nightly, beta)."
        default: "stable"
      components:
        required: false
        type: string
        description: "Comma-separated list of Rust components to install (e.g., rustfmt, clippy)."
        default: "clippy,rustfmt"
      target:
        required: false
        type: string
        description: "Comma-separated list of additional Rust compilation targets."
        default: ""
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"
    secrets:
      DAGGER_CLOUD_TOKEN:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # de0fac2, https://github.com/actions/checkout/releases/latest
      - uses: mbround18/gh-reusable/.github/actions/dagger-run@main
        with:
          call: >-
            rust-build-and-test
            --source=.
            --toolchain=${{ inputs.toolchain }}
            --components=${{ inputs.components }}
            --target=${{ inputs.target }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
