name: "Rust Build and Test"

on:
  workflow_call:
    inputs:
      toolchain:
        required: false
        type: string
        description: "Rust toolchain to use (e.g., stable, nightly, beta)."
        default: "stable"
      components:
        required: false
        type: string
        description:
          "Comma-separated list of Rust components to install (e.g., rustfmt,
          clippy)."
        default: "clippy rustfmt"
      target:
        required: false
        type: string
        description: "Comma-separated list of additional Rust compilation targets."
        default: ""
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"

env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # de0fac2, https://github.com/actions/checkout/releases/latest
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 48b55a0, https://github.com/actions/setup-node/releases/latest
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - name: Run Rust workflow in Dagger
        uses: dagger/dagger-for-github@v8
        env:
          INPUT_TOOLCHAIN: ${{ inputs.toolchain }}
          INPUT_COMPONENTS: ${{ inputs.components }}
          INPUT_TARGET: ${{ inputs.target }}
        with:
          version: latest
          verb: run
          args: pnpm --filter @gh-reusable/dagger-pipelines run dagger:workflow --id rust-build-n-test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
