name: "Test | Ensure Repository"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "actions/ensure-repository/**"
      - ".github/workflows/test-ensure-repository.yml"
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - "actions/ensure-repository/**"
      - ".github/workflows/test-ensure-repository.yml"

jobs:
  test_ensure_repository:
    name: Test Ensure Repository
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/ensure-repository
        with:
          repository: mbround18/gh-reusable
