name: "Test | Docker Release Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  ensure_repository:
    name: Ensure Repository
    runs-on: ubuntu-latest
    steps:
      - name: Verify Repo is mbround18/gh-reusable
        uses: mbround18/gh-reusable/actions/ensure-repository@v0.0.6

  run_npm_tests:
    name: Run npm tests for Docker Facts
    runs-on: ubuntu-latest
    needs: ensure_repository
    defaults:
      run:
        working-directory: actions/docker-facts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: actions/docker-facts/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  call_docker_release:
    name: Call Docker Release Workflow
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@docker-facts-tests
    with:
      image: "mbround18/gh-reusable-testing" # Specify the test image name here
      ghcr: true
      working-directory: "tests/docker"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  call_docker_release_compose_1:
    name: Call Docker Release Workflow (Compose)
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@docker-facts-tests
    with:
      image: "mbround18/gh-reusable-testing-compose" # Specify the test image name here
      ghcr: true
      compose: true
      working-directory: "tests/docker-compose"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  call_docker_release_compose_2:
    name: Call Docker Release Workflow (Compose)
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@docker-facts-tests
    with:
      image: "mbround18/gh-reusable-testing-compose2" # Specify the test image name here
      ghcr: true
      compose: true
      working-directory: "tests/docker-compose"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
