name: "Test | Docker Release Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  call_docker_release:
    name: Call Docker Release Workflow
    uses: ./.github/workflows/docker-release.yaml
    with:
      image: "mbround18/gh-reusable-testing" # Specify the test image name here
      dockerfile: "tests/docker/Dockerfile" # Path to the seeded Dockerfile
      ghcr: true
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
