name: "Test | Rust Build and Test Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  call_build_and_test_workflow:
    name: Call Rust Build and Test Workflow
    uses: ./.github/workflows/rust-build-n-test.yml
