name: "Test | Rust Build and Test Workflow"

on:
  pull_request:
    branches:
      - main
    paths:
      - "actions/setup-rust/**"
      - ".github/workflows/rust-build-n-test.yml"
      - ".github/workflows/test-rust-build-n-test.yml"
      - "**/*.rs"
      - "**/*.toml"
      - "**/Cargo.lock"
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - "actions/setup-rust/**"
      - ".github/workflows/rust-build-n-test.yml"
      - ".github/workflows/test-rust-build-n-test.yml"
      - "**/*.rs"
      - "**/*.toml"
      - "**/Cargo.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ensure_repository:
    name: Ensure Repository
    runs-on: ubuntu-latest
    steps:
      - name: Verify Repo is mbround18/gh-reusable
        uses: mbround18/gh-reusable/actions/ensure-repository@v0.0.6
  call_build_and_test_workflow:
    name: Call Rust Build and Test Workflow
    uses: ./.github/workflows/rust-build-n-test.yml
    with:
      runs-on: ubuntu-latest
