name: "Test | Install CLI Action"

on:
  # Trigger when a pull request is opened or synchronized
  pull_request:
    branches:
      - main

  # Trigger when code is pushed to the 'main' branch
  push:
    branches:
      - main

jobs:
  install-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - repository: "schollz/croc"
            version: "v10.0.12"
            asset: "croc_%VERSION%_Linux-64bit.tar.gz"
            test-command: "croc --version"
          - repository: "astral-sh/uv"
            asset: "uv-x86_64-unknown-linux-gnu.tar.gz"
            test-command: uv --version
          - repository: jqlang/jq
            asset: jq-linux-amd64
            override-name: "jq"
            test-command: jq --version
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CLI
        uses: ./actions/install-cli
        with:
          repository: ${{ matrix.config.repository }}
          version: ${{ matrix.config.version }}
          asset: ${{ matrix.config.asset }}
          override-name: ${{ matrix.config.override-name }}

      # Verify Croc CLI Installation
      - name: Verify CLI
        run: |
          ${{ matrix.config.test-command }}
