name: "Update README"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "actions/**/action.yml"
      - "README.md"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  update_readme:
    name: Update README
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # de0fac2, https://github.com/actions/checkout/releases/latest

      - uses: mbround18/gh-reusable/actions/github-catalog@main

      - name: Update Readme
        run: |
          cat README.md > $GITHUB_STEP_SUMMARY
