name: "Update README"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "actions/**/action.yml"
      - "README.md"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_readme:
    name: Update README
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # de0fac2, https://github.com/actions/checkout/releases/latest

      - uses: ./actions/github-catalog

      - name: Update Readme
        run: |
          cat README.md > $GITHUB_STEP_SUMMARY
