name: "Update README"

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: "GitHub runner to use for this workflow."
        default: "ubuntu-latest"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "actions/**/action.yml"

permissions:
  contents: write

jobs:
  update_readme:
    name: Update README
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./actions/github-catalog

      - name: Update Readme
        run: |
          cat README.md > $GITHUB_STEP_SUMMARY
